FROM node:20-alpine AS installer

# Executa como usuário não-root
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

USER nodejs
WORKDIR /app

COPY --chown=nodejs:nodejs package*.json ./
COPY --chown=nodejs:nodejs install.ts ./

RUN npx ts-node install.ts

FROM node:20-alpine AS runtime
COPY --from=installer --chown=nodejs:nodejs /app/node_modules ./node_modules
COPY --chown=nodejs:nodejs . .

USER nodejs
CMD ["node", "dist/index.js"]